services:
  abiotic-server:
    build:
      context: 'docker'
    image: abiotic-ds-image:1.0
    container_name: abiotic-ds
    volumes:
      - "./game:/home/steam/game"
      - "./gameSaves:/home/steam/game/AbioticFactor/Saved/SaveGames/Server"
      - "./wine:/home/steam/.wine"
    environment:
      USER_UID: "${PUID:-1000}"
      USER_GID: "${PGID:-1000}"
      ServerPassword: "${SERVER_PASSWORD}"
      SteamServerName: "${STEAM_SERVER_NAME}"
      NoAsyncLoadingThread: "${NO_ASYNC_LOADING_THREAD:-true}"
      UsePerfThreads: "${USE_PERF_THREADS:-true}"
      MaxServerPlayers: "${MAX_SERVER_PLAYERS:-3}"
      UseQueryPort: "${USE_QUERY_PORT:-true}"
      QueryPort: "${QUERY_PORT:-27015}"
      WorldSaveName: "${WORLD_SAVE_NAME:-Cascade}"
    restart: unless-stopped
    ports:
      - "${PORT:-7777}:7777/udp"
      - "${QUERY_PORT:-27015}:${QUERY_PORT:-27015}/udp"
